//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersections.Billing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intersections.Billing.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number is invalid.
        /// </summary>
        internal static string cardNumberInvalid {
            get {
                return ResourceManager.GetString("cardNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number must be between 9 and 20 digits.
        /// </summary>
        internal static string cardNumberLength {
            get {
                return ResourceManager.GetString("cardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number is required.
        /// </summary>
        internal static string cardNumberRequired {
            get {
                return ResourceManager.GetString("cardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is invalid.
        /// </summary>
        internal static string cityInvalid {
            get {
                return ResourceManager.GetString("cityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be between 2 and 40 characters.
        /// </summary>
        internal static string cityLength {
            get {
                return ResourceManager.GetString("cityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        internal static string cityRequired {
            get {
                return ResourceManager.GetString("cityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is invalid.
        /// </summary>
        internal static string countryInvalid {
            get {
                return ResourceManager.GetString("countryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country must be 2 characters.
        /// </summary>
        internal static string countryLength {
            get {
                return ResourceManager.GetString("countryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string countryRequired {
            get {
                return ResourceManager.GetString("countryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV Number is invalid.
        /// </summary>
        internal static string cvvInvalid {
            get {
                return ResourceManager.GetString("cvvInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV Number must be between 3 and 4 digits.
        /// </summary>
        internal static string cvvLength {
            get {
                return ResourceManager.GetString("cvvLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV Number is required.
        /// </summary>
        internal static string cvvRequired {
            get {
                return ResourceManager.GetString("cvvRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month is invalid.
        /// </summary>
        internal static string expirationMonthInvalid {
            get {
                return ResourceManager.GetString("expirationMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month must be in MM format.
        /// </summary>
        internal static string expirationMonthLength {
            get {
                return ResourceManager.GetString("expirationMonthLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month is required.
        /// </summary>
        internal static string expirationMonthRequired {
            get {
                return ResourceManager.GetString("expirationMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year is invalid.
        /// </summary>
        internal static string expirationYearInvalid {
            get {
                return ResourceManager.GetString("expirationYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year must be in YYYY format.
        /// </summary>
        internal static string expirationYearLength {
            get {
                return ResourceManager.GetString("expirationYearLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year is required.
        /// </summary>
        internal static string expirationYearRequired {
            get {
                return ResourceManager.GetString("expirationYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is invalid.
        /// </summary>
        internal static string firstNameInvalid {
            get {
                return ResourceManager.GetString("firstNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name must be between 2 and 40 characters.
        /// </summary>
        internal static string firstNameLength {
            get {
                return ResourceManager.GetString("firstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        internal static string firstNameRequired {
            get {
                return ResourceManager.GetString("firstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is invalid.
        /// </summary>
        internal static string lastNameInvalid {
            get {
                return ResourceManager.GetString("lastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name must be between 2 and 40 characters.
        /// </summary>
        internal static string lastNameLength {
            get {
                return ResourceManager.GetString("lastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        internal static string lastNameRequired {
            get {
                return ResourceManager.GetString("lastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is invalid.
        /// </summary>
        internal static string postalCodeInvalid {
            get {
                return ResourceManager.GetString("postalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code must be 5 digits.
        /// </summary>
        internal static string postalCodeLength {
            get {
                return ResourceManager.GetString("postalCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required.
        /// </summary>
        internal static string postalCodeRequired {
            get {
                return ResourceManager.GetString("postalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is invalid.
        /// </summary>
        internal static string stateInvalid {
            get {
                return ResourceManager.GetString("stateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State must be 2 characters.
        /// </summary>
        internal static string stateLength {
            get {
                return ResourceManager.GetString("stateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        internal static string stateRequired {
            get {
                return ResourceManager.GetString("stateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address Line 1 must be between 3 and 40 characters.
        /// </summary>
        internal static string street1Length {
            get {
                return ResourceManager.GetString("street1Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address Line 1 is required .
        /// </summary>
        internal static string street1Required {
            get {
                return ResourceManager.GetString("street1Required", resourceCulture);
            }
        }
    }
}
